### ISSUE TITLE
Does not build - issue with RUTILS.CORE::ARGLIST

### ISSUE THREAD

**Issue by quicklisp** [vseloved/rutils#25]
http://report.quicklisp.org/2015-09-09/failure-report/rutils.html#rutils has a log. I get an error that RUTILS.CORE::ARGLIST is not a function.

**Comment by vseloved** [comment]
Thanks a lot! That was a huge oversight on my part. Fixed in the last update.

**Comment by quicklisp** [comment]
Now I get an umatched close paren :~(

**Comment by vseloved** [comment]
fixed
