### ISSUE TITLE
Doesn't build - bad MAPCAR use

### ISSUE THREAD

**Issue by quicklisp** [vseloved/rutils#27]
I get this today:

    ;     (MAPCAR
    ;      (RUTILS.READTABLE::TRIVIAL-POSITIONAL-LAMBDA
    ;       (RUTILSX.BIND::SMART-SLOT-VALUE RUTILS.READTABLE:% RUTILSX.BIND::OBJ)))
    ; 
    ; caught WARNING:
    ;   The function was called with one argument, but wants at least two.

**Comment by vseloved** [comment]
Thanks, fixed
