### ISSUE TITLE
Iterate collect result-type inconsistent

### ISSUE THREAD

**Issue by djeis97** [vseloved/rutils#31]
In the version of iterate in contrib, the result type is not quoted in the macroexpansion so that it can "be non-literal" (Line 3069 of contrib/iter.lisp). However, in order to deal with the "maybe quoted" stuff, earlier in `return-collection-code` one level of quotation is stripped off the `:result-type` argument (Line 3003). This means that, in order to pass a literal type here, it has to be double quoted.

Example:
``` Common-Lisp
(rutilsx:iter
  (:repeat 5)
  (:collect "foo" :result-type ''vector))
```

As opposed to:
``` Common-Lisp
(rutilsx:iter
  (:repeat 5)
  (:collect "foo" :result-type 'vector))
```
Or:
``` Common-Lisp
(rutilsx:iter
  (:repeat 5)
  (:collect "foo" :result-type vector))
```
Which both result in `(coerce #:result vector)` and error out.

**Comment by vseloved** [comment]
I guess, this code was taken from original iterate. Can you provide a fix?
