### ISSUE TITLE
Make it possible to escape newlines in the #/ reader macro

### ISSUE THREAD

**Issue by libre-man** [vseloved/rutils#34]
As these should be used in documentation strings it might be really useful escape newlines as they don't look pretty (especially with whitespace) in many editors. Something like ~ at the end like format has would be really nice.

**Comment by vseloved** [comment]
Hi, thanks for the suggestion.
Sorry for taking some time to reply, I was contemplating this idea, and I don't think it makes a lot of sense. For the specific use case of docstrings, I believe, post-processing is always possible if it's necessary to display them somewhere outside of the editor (and in the editor additional escaping will only clutter the view). As for the other use cases, `format` is more appropriate when you need something non-literal. Besides, it will add complexity to the implementation.
