### ISSUE TITLE
Reader Macros don't work

### ISSUE THREAD

**Issue by itmuckel** [vseloved/rutils#40]
I put `(:use :rutilsx)` in my package definition and the ? operator also works.

But when I try to use the literal syntax for hashtables like this:
```lisp
  (setf *state* #h(
                   :spaceship-acceleration 0.2
                   :max-speed 16.0
                   :inc-speed-p nil
                   :dec-speed-p nil
                   :rotate-delta 0.0
                   :player-dead-p nil
                   :init-timeout-millis 3000
                   :game-start-time (get-millis)
                   :spaceship nil))
```
I get
```
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     no dispatch function defined for #\H
```

Am I using it wrong?

**Comment by vseloved** [comment]
You need to add `(named-readtables:in-readtable rutilsx-readtable)` at the beginning of the file with such code or in the REPL before evaluating this code

**Comment by itmuckel** [comment]
Thank you, that worked! Could be a nice addition to the docs page. I'm relatively new to lisp, but I think reader macros are for advanced lispers and it should be mentioned how to activate the literal syntax somewhere. Maybe somewhere, where it gets extracted into quickdocs or at the top of `core/readtable.lisp`.

By the way: Thank you for this awesome library! 👽

**Comment by vseloved** [comment]
You're welcome. I'm glad you find it handy. Hopefully, reading the tutorial will help make it even more useful
