### ISSUE TITLE
generic-elt doesn't work for plists

### ISSUE THREAD

**Issue by itmuckel** [vseloved/rutils#41]
I have a plist like
```lisp
(defparameter my-plist (list :a 1 :b 2 :c (list :a 4)))
```
`(? my-plist :a)` returns an error, because it tries to do
```lisp
(nthcdr :a (:a 1 :b 2 :c (:a 4)))
```

Is it viable to make a distinction between regular lists and plists/alists in `(generic-elt ((obj list)...)))` or would the decrease in performance not be worth it?

**Comment by vseloved** [comment]
There's no way to distinguish between a plain plist and a normal list. Originally, I had this functionality, but after hitting some unpleasant surprise with it I had to revert it to normal list access.

P.S. btw, here's a tutorial you have requested (if I'm not mistaken :) : https://gist.github.com/vseloved/9c6e36f2fa89f4accf3f3cbc371b3ce1

**Comment by itmuckel** [comment]
About the tutorial: Ah, yes, perfect!

About this issue: Okay. Then I have to live with it. 👽
