### ISSUE TITLE
rutilsx system does not build

### ISSUE THREAD

**Issue by quicklisp** [vseloved/rutils#42]
I get this:```
Package RUTILSX.BIND does not exist. Line: 68, Column: 39, File-Position: 2282 Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/quicklisp/quicklisp-controller/dist/build-cache/rutils/0261dca135efb32cd339cef9a377774e31782b4d/rutils-20190830-git/contrib/generators.lisp" {1006421253}>```

Full log here: http://report.quicklisp.org/2019-08-30/failure-report/rutils.html#rutilsx

**Comment by vseloved** [comment]
fixed
