### ISSUE TITLE
setf macro issue

### ISSUE THREAD

**Issue by quicklisp** [vseloved/rutils#55]
https://github.com/vseloved/rutils/blob/0ff2b061f3769894d8084cef3000c28aebef7960/core/abbr.lisp#L100

I get this:

```; caught WARNING:
;   defining setf macro for ? when (SETF ?) was previously treated as a function
```

**Comment by quicklisp** [comment]
This doesn't happen directly in rutils, but when compiling other systems. Logs here:

* http://report.quicklisp.org/2020-06-15/failure-report/cl-bson.html#cl-bson-test
* http://report.quicklisp.org/2020-06-15/failure-report/lack.html#lack-session-store-redis

**Comment by vseloved** [comment]
thanks for the report, thos should be fixed by the latest update
