### ISSUE TITLE
with/bind ignorable variable `_' generates "unused lexical variable" compiler warning

### ISSUE THREAD

**Issue by mirkov** [vseloved/rutils#56]
By way of example, 
```
(rutils:bind (((d _ e &rest f) '(4 0 5 12 13 14 15)))
  (list d e f))
```
generates
```
;Compiler warnings :
;   In an anonymous lambda form: Unused lexical variable _
```
This is on 
```
CL-USER> (lisp-implementation-type)
"Clozure Common Lisp"
CL-USER> (lisp-implementation-version)
"Version 1.11-r16635  (WindowsX8664)"
```

**Comment by vseloved** [comment]
Hi,
the reason for this is that you haven't imported the `_` symbol and it matched the symbol name. I have changed the code to match with `string=`, which is more ntuitive, I agree.

**Comment by jcguu95** [comment]
As @mirkov pointed out, the issue _may_ not have been completely solved yet (issue: https://github.com/vseloved/rutils/issues/60). ( Note however that in the issue no reproducing step is provided.) 

Just as a note for future progress: the relevant fix @vseloved did was: https://github.com/vseloved/rutils/commit/eedd9b2b0afc90c98a2a2756f35b000743aa5885
