### ISSUE TITLE
Clojure macros

### ISSUE THREAD

**Issue by aluuu** [vseloved/rutils#9]
Hello.

That must be useful to add «threading» macros [->](http://clojuredocs.org/clojure_core/clojure.core/-%3E) and [->>](http://clojuredocs.org/clojure_core/clojure.core/-%3E%3E).
What do you think about it?

**Comment by EuAndreh** [comment]
Wouldn't it be easier to just use [arrow-macros](https://github.com/hipeta/arrow-macros/)?

**Comment by vseloved** [comment]
I guess, it's the same choice as using (and depending on) full-fledged [anaphora](http://www.cliki.net/anaphora) or a smaller set of anaphoric macros from rutils. I think, both approaches are fine :)

**Comment by EuAndreh** [comment]
I see.
